[config]
schemaVersion = "0.0.1"


[package]
namespace = "Jowday"
name = "Perfectoinist"
versionNumber = "0.1.0"
description = "Plugin for BoonBuddy. Adds a new rarity level called 'Perfect'."
websiteUrl = "https://github.com/The-Black-Lodge/JowdayPerfectoinist"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-ENVY = "1.0.0"
SGG_Modding-Chalk = "2.0.2"
SGG_Modding-ReLoad = "1.0.1"
SGG_Modding-ModUtil = "3.1.1"
Jowday-BoonBuddy = "0.6.9"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[[build.copy]]
source = "./packages"
target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
